version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # opcional: ignore:
    # - dependency-name: "some-dependency"
    #   versions: ["1.x"]